spring.application.name=notification
server.port=3010

# ===============================
# = Mail Configuration (Gmail)
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.asp.project@gmail.com
spring.mail.password=slwa eajy mteh dxzx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# = Custom App Mail Property
# ===============================

app.mail.from=ro-reply@ucmo.edu
